Algoritmo "semnome"
// Faça um algoritmo que leia três notas e faça a
// média aritmética simples e mostre ao usuário.
Var
     nota1, nota2, nota3 :inteiro
     media : real
Inicio
    Escreval("Informe a nota1:")
    Leia(nota1)
    Escreval("Informe a nota2:")
    Leia(nota2)
    Escreval("Informe a nota3:")
    Leia(nota3)
    media <- (nota1+nota2+nota3)/3
    Escreval("A média é ", media)

Fimalgoritmo